#!/bin/sh

SOURCE="$PWD"
DEST="/var/www/elliedixonmusic"
cp $DEST -r /var/www/edmold
rm -rf $DEST
mkdir $DEST
cp $SOURCE/* -r $DEST
cp $SOURCE/.htaccess $DEST
rm $DEST/deploy*
rm -rf $DEST/sourcefiles
rm $DEST/staging*
